name: Create Release
on:
  push:
    tags:
      - 'v*' 
permissions:
  deployments: write
  contents: write
  packages: write
  
jobs:
  release-tag:    
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 16.x, 14.x, 12.x]

    runs-on: ${{ matrix.os }}    
    
    steps:      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build package
        run: |
          npm install
          npm start
          tar czvf dist.tar.gz dist
          cp package.json dist/
          cp README.md dist/
          cp LICENSE dist/
          cp main.d.ts dist/
          cp CHANGELOG.md dist/

      - name: Set release version        
        uses: actions/checkout@main

      - name: Create release tag
        id: create_release
        uses: actions/create-release@v1   #actions/create-release@latest
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Please refer to the [README](https://github.com/xkid1/dotvar/blob/main/README.md) for details.
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.tar.gz

      - name: Upload package.json
        uses: actions/upload-artifact@v2
        with:
          name: package.json
          path: dist/package.json

      - name: Upload README.md
        uses: actions/upload-artifact@v2
        with:
          name: README.md
          path: dist/README.md

      - name: Upload LICENSE
        uses: actions/upload-artifact@v2
        with:
          name: LICENSE
          path: dist/LICENSE

      - name: Upload main.d.ts
        uses: actions/upload-artifact@v2
        with:
          name: main.d.ts
          path: dist/main.d.ts

      - name: Upload CHANGELOG.md
        uses: actions/upload-artifact@v2
        with:
          name: CHANGELOG.md
          path: dist/CHANGELOG.md

      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: release-assets
          path: |   
           dist/





